# Spring Boot Application Properties
spring.application.name=capstonepoc
server.port=9080

# Qdrant Configuration
qdrant.host=localhost
qdrant.port=6334
qdrant.collection-name=research_works
qdrant.dimension=768

# Ollama Configuration (if needed)
ollama.base-url=http://localhost:11434
ollama.model-name=nomic-embed-text

# Logging
logging.level.root=INFO
logging.level.com.example.capstonepoc=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/capstone_db
spring.datasource.username=capstone_user
spring.datasource.password=atmarupa1234
spring.datasource.driver-class-name=org.postgresql.Driver

# For your POC: Automatically create tables from @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
